# Generated by Django 4.0.3 on 2022-03-23 16:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_alter_log_date_alter_log_id_alter_log_time_in_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 3, 23, 18, 52, 38, 12603)),
        ),
        migrations.AlterField(
            model_name='log',
            name='time_in',
            field=models.TimeField(default=datetime.datetime(2022, 3, 23, 18, 52, 38, 12603)),
        ),
    ]
